import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="flex min-h-screen sm:items-start md:items-center">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>

      <div className="flex items-start justify-start flex-1 w-screen bg-blue-400">
        glen
      </div>
    </div>
  );
}
