import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="flex justify-start sm:justify-center">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <div class="wp-site-blocks"><div class="wp-block-template-part">
<div class="wp-container-61ddebb6e3bf2 wp-block-group gapless-group">

<div class="wp-container-61ddebb6e3184 wp-block-group site-header site-header-linear alignfull" style="padding-bottom:var(--wp--custom--gap--vertical);padding-top:var(--wp--custom--gap--vertical)">

	
	<div class="wp-container-61ddebb6e101f wp-block-group site-brand">
		

		
		<div class="wp-container-61ddebb6e0c69 wp-block-group site-words-stack-small">
			<h1 class="wp-block-site-title"><a href="https://quadratblackdemo.wordpress.com?demo" rel="home" aria-current="page">Quadrat Black</a></h1>
			<p style="font-size: var(--wp--custom--font-sizes--tiny);" class="wp-block-site-tagline">A theme for blogs and podcasts</p>
		</div>
		
	</div>
	

	<nav class="wp-container-61ddebb6e2d77 is-responsive items-justified-right blockbase-responsive-navigation-linear wp-block-navigation"><button aria-haspopup="true" aria-label="Open menu" class="wp-block-navigation__responsive-container-open " data-micromodal-trigger="modal-61ddebb6e285a"><svg width="24" height="24" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" role="img" aria-hidden="true" focusable="false"><rect x="4" y="7.5" width="16" height="1.5"></rect><rect x="4" y="15" width="16" height="1.5"></rect></svg></button>
			<div class="wp-block-navigation__responsive-container  " style="" id="modal-61ddebb6e285a">
				<div class="wp-block-navigation__responsive-close" tabindex="-1" data-micromodal-close="">
					<div class="wp-block-navigation__responsive-dialog" aria-label="Menu">
							<button aria-label="Close menu" data-micromodal-close="" class="wp-block-navigation__responsive-container-close"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" role="img" aria-hidden="true" focusable="false"><path d="M13 11.8l6.1-6.3-1-1-6.1 6.2-6.1-6.2-1 1 6.1 6.3-6.5 6.7 1 1 6.5-6.6 6.5 6.6 1-1z"></path></svg></button>
						<div class="wp-block-navigation__responsive-container-content" id="modal-61ddebb6e285a-content">
							<ul class="wp-block-navigation__container"><li class=" wp-block-navigation-item  menu-item menu-item-type-post_type menu-item-object-page wp-block-navigation-link"><a class="wp-block-navigation-item__content" href="https://quadratblackdemo.wordpress.com/blog/?demo" title=""><span class="wp-block-navigation-item__label">Blog</span></a></li><li class=" wp-block-navigation-item  menu-item menu-item-type-post_type menu-item-object-page wp-block-navigation-link"><a class="wp-block-navigation-item__content" href="https://quadratblackdemo.wordpress.com/podcast/?demo" title=""><span class="wp-block-navigation-item__label">Podcast</span></a></li><li class=" wp-block-navigation-item  menu-item menu-item-type-post_type menu-item-object-page wp-block-navigation-link"><a class="wp-block-navigation-item__content" href="https://quadratblackdemo.wordpress.com/about/?demo" title=""><span class="wp-block-navigation-item__label">About</span></a></li><li class=" wp-block-navigation-item  menu-item menu-item-type-post_type menu-item-object-page wp-block-navigation-link"><a class="wp-block-navigation-item__content" href="https://quadratblackdemo.wordpress.com/contact/?demo" title=""><span class="wp-block-navigation-item__label">Contact</span></a></li></ul>
						</div>
					</div>
				</div>
			</div></nav>

</div>


<div class="wp-block-template-part">
<div style="height:136px" aria-hidden="true" class="wp-block-spacer"></div>
</div>

</div>

</div>


<div style="height:60px" aria-hidden="true" class="wp-block-spacer"></div>



<main class="wp-container-61ddebb6ec457 wp-block-group" id="wp--skip-link--target">
	<div class="wp-container-61ddebb6ec07f entry-content wp-block-post-content">
<div class="wp-block-columns alignwide">
<div class="wp-block-column" style="flex-basis:900px;">
<h1>The podcast for women about all the things that matter.</h1>



<p class="has-normal-font-size">#QuadratPodcast</p>
</div>
</div>



<div style="height:170px;" aria-hidden="true" class="wp-block-spacer"></div>



<div style="height:30px;" aria-hidden="true" class="wp-block-spacer"></div>



<div class="wp-container-61ddebb6e826f wp-block-query alignwide"><ul class="wp-container-61ddebb6e7def is-flex-container columns-2 wp-block-post-template"><li class="wp-block-post post-6 post type-post status-publish format-standard has-post-thumbnail hentry category-uncategorized">

<div class="wp-container-61ddebb6e5eea wp-container-61ddebb6e5ad5 wp-block-group vertical-query-pattern" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0;"><figure class="mb-0 wp-block-post-featured-image"><img width="1024" height="913" src="https://quadratblackdemo.files.wordpress.com/2021/12/introspection-scaled-1.jpeg?w=1024" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" loading="lazy" srcset="https://quadratblackdemo.files.wordpress.com/2021/12/introspection-scaled-1.jpeg?w=1024 1024w, https://quadratblackdemo.files.wordpress.com/2021/12/introspection-scaled-1.jpeg?w=150 150w, https://quadratblackdemo.files.wordpress.com/2021/12/introspection-scaled-1.jpeg?w=300 300w, https://quadratblackdemo.files.wordpress.com/2021/12/introspection-scaled-1.jpeg?w=768 768w, https://quadratblackdemo.files.wordpress.com/2021/12/introspection-scaled-1.jpeg 1600w" sizes="(max-width: 1024px) 100vw, 1024px" data-attachment-id="15" data-permalink="https://quadratblackdemo.wordpress.com/2021/12/21/episode-3-a-cycle-of-emotions/placeholder-image-2/" data-orig-file="https://quadratblackdemo.files.wordpress.com/2021/12/introspection-scaled-1.jpeg" data-orig-size="1600,1427" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="Placeholder Image" data-image-description="" data-image-caption="" data-medium-file="https://quadratblackdemo.files.wordpress.com/2021/12/introspection-scaled-1.jpeg?w=300" data-large-file="https://quadratblackdemo.files.wordpress.com/2021/12/introspection-scaled-1.jpeg?w=1024"></figure>


<div class="wp-block-cover has-tertiary-background-color has-background-dim" style="margin-top:0;padding-top:30px;padding-right:40px;padding-bottom:20px;padding-left:40px;min-height:360px;"><div class="wp-block-cover__inner-container"><h2 class="has-text-color has-primary-color wp-block-post-title"><a href="https://quadratblackdemo.wordpress.com/2021/12/21/episode-3-a-cycle-of-emotions/?demo" target="_blank" rel="">Episode 3: A Cycle of&nbsp;Emotions</a></h2>

<div class="has-text-color has-primary-color wp-block-post-excerpt has-small-font-size"><p class="wp-block-post-excerpt__excerpt">“Do we need periods if they make us crazy?”, Sarah asks. Hint: yes, we do. We reached out to our friend Diana Roth, an endocrinologist specialised in women’s hormonal health to know how menstrual cycles impact women’s brains and emotions. </p></div></div></div>
</div>

</li><li class="wp-block-post post-7 post type-post status-publish format-standard has-post-thumbnail hentry category-uncategorized">

<div class="wp-container-61ddebb6e760d wp-container-61ddebb6e715c wp-block-group vertical-query-pattern" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0;"><figure class="mb-0 wp-block-post-featured-image"><img width="1024" height="623" src="https://quadratblackdemo.files.wordpress.com/2021/12/leadership.jpeg?w=1024" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" loading="lazy" srcset="https://quadratblackdemo.files.wordpress.com/2021/12/leadership.jpeg 1024w, https://quadratblackdemo.files.wordpress.com/2021/12/leadership.jpeg?w=150 150w, https://quadratblackdemo.files.wordpress.com/2021/12/leadership.jpeg?w=300 300w, https://quadratblackdemo.files.wordpress.com/2021/12/leadership.jpeg?w=768 768w" sizes="(max-width: 1024px) 100vw, 1024px" data-attachment-id="20" data-permalink="https://quadratblackdemo.wordpress.com/2021/12/21/episode-2-female-leaders-where-are-they/placeholder-image-5/" data-orig-file="https://quadratblackdemo.files.wordpress.com/2021/12/leadership.jpeg" data-orig-size="1024,623" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="Placeholder Image" data-image-description="" data-image-caption="" data-medium-file="https://quadratblackdemo.files.wordpress.com/2021/12/leadership.jpeg?w=300" data-large-file="https://quadratblackdemo.files.wordpress.com/2021/12/leadership.jpeg?w=1024"></figure>


<div class="wp-block-cover has-tertiary-background-color has-background-dim" style="margin-top:0;padding-top:30px;padding-right:40px;padding-bottom:20px;padding-left:40px;min-height:360px;"><div class="wp-block-cover__inner-container"><h2 class="has-text-color has-primary-color wp-block-post-title"><a href="https://quadratblackdemo.wordpress.com/2021/12/21/episode-2-female-leaders-where-are-they/?demo" target="_blank" rel="">Episode 2: Female Leaders, Where Are&nbsp;They?</a></h2>

<div class="has-text-color has-primary-color wp-block-post-excerpt has-small-font-size"><p class="wp-block-post-excerpt__excerpt">After years of revolution, the big question remains: why aren’t there more women in leadership? Sarah and Olivia get deep into the subject. </p></div></div></div>
</div>

</li></ul></div>



<div class="wp-container-61ddebb6ea7df wp-block-query alignwide"><ul class="wp-container-61ddebb6ea388 wp-block-post-template"><li class="wp-block-post post-8 post type-post status-publish format-standard has-post-thumbnail hentry category-uncategorized">

<div class="wp-container-61ddebb6e9cb3 wp-container-61ddebb6e9893 wp-block-group horizontal-query-pattern"><figure class="image-no-margin mb-0 wp-block-post-featured-image"><img width="1024" height="623" src="https://quadratblackdemo.files.wordpress.com/2021/12/screen-usage.jpeg?w=1024" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" loading="lazy" srcset="https://quadratblackdemo.files.wordpress.com/2021/12/screen-usage.jpeg 1024w, https://quadratblackdemo.files.wordpress.com/2021/12/screen-usage.jpeg?w=150 150w, https://quadratblackdemo.files.wordpress.com/2021/12/screen-usage.jpeg?w=300 300w, https://quadratblackdemo.files.wordpress.com/2021/12/screen-usage.jpeg?w=768 768w" sizes="(max-width: 1024px) 100vw, 1024px" data-attachment-id="21" data-permalink="https://quadratblackdemo.wordpress.com/2021/12/21/episode-1-how-screens-affect-hormones/placeholder-image-6/" data-orig-file="https://quadratblackdemo.files.wordpress.com/2021/12/screen-usage.jpeg" data-orig-size="1024,623" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="Placeholder Image" data-image-description="" data-image-caption="" data-medium-file="https://quadratblackdemo.files.wordpress.com/2021/12/screen-usage.jpeg?w=300" data-large-file="https://quadratblackdemo.files.wordpress.com/2021/12/screen-usage.jpeg?w=1024"></figure>


<div class="wp-block-cover has-tertiary-background-color has-background-dim horizontal-query-pattern" style="margin-top:0;padding-top:30px;padding-right:40px;padding-bottom:30px;padding-left:40px;min-height:360px;"><div class="wp-block-cover__inner-container"><h2 class="has-text-color has-primary-color wp-block-post-title"><a href="https://quadratblackdemo.wordpress.com/2021/12/21/episode-1-how-screens-affect-hormones/?demo" target="_blank" rel="">Episode 1: How Screens Affect&nbsp;Hormones</a></h2>

<div class="has-text-color has-primary-color wp-block-post-excerpt has-small-font-size"><p class="wp-block-post-excerpt__excerpt">In this episode, Sarah and Olivia talk with female hormone specialist Diana Roth about the impact that gadgets and technology have on hormone and fertility health. </p></div></div></div>
</div>

</li></ul></div>



<div style="height:170px;" aria-hidden="true" class="wp-block-spacer"></div>



<div class="wp-container-61ddebb6eafae wp-block-group alignwide">
<p>The Hosts</p>



<h2>Samantha and Olivia are both writers and activists.</h2>



<div style="height:36px;" aria-hidden="true" class="wp-block-spacer"></div>



<div class="wp-container-61ddebb6eabda wp-block-buttons">
<div class="wp-block-button"><a class="wp-block-button__link">Learn More</a></div>
</div>
</div>



<div style="height:170px;" aria-hidden="true" class="wp-block-spacer"></div>



<div class="wp-block-columns alignwide">
<div class="wp-block-column">
<h3>Join the Community</h3>



<p>We’re thrilled to have you here! Now, if you don’t want to miss an article or an episode, you can subscribe to our newsletter.</p>
</div>



<div class="wp-block-column is-vertically-aligned-center subscription-column">
<div class="wp-block-jetpack-subscriptions wp-block-jetpack-subscriptions__supports-newline wp-block-jetpack-subscriptions__use-newline"><div class="jetpack_subscription_widget">
			<form action="https://subscribe.wordpress.com" method="post" accept-charset="utf-8" id="subscribe-blog">
								<p id="subscribe-email">
					<label id="subscribe-field-label" for="subscribe-field" class="screen-reader-text">
						Email Address:					</label>

					<input type="email" name="email" style="font-size: 16px; padding: 15px 23px 15px 23px; border-radius: 0px; border-width: 1px;" placeholder="Enter your email address" value="" id="subscribe-field">				</p>

				<p id="subscribe-submit">
                    <input type="hidden" name="action" value="subscribe">
                    <input type="hidden" name="blog_id" value="201012771">
                    <input type="hidden" name="source" value="https://quadratblackdemo.wordpress.com/?demo=true&amp;iframe=true&amp;theme_preview=true&amp;calypso_token=3086cafe-ce6d-4f8a-a073-4447253d7278">
                    <input type="hidden" name="sub-type" value="widget">
					<input type="hidden" name="redirect_fragment" value="subscribe-blog">
					<input type="hidden" id="_wpnonce" name="_wpnonce" value="a89882ebe2">                    <button type="submit" class="wp-block-button__link" style="font-size: 16px; padding: 15px 23px 15px 23px; margin-top: 10px; border-radius: 0px; border-width: 1px;">
	                    Subscribe                    </button>
                </p>
            </form>
			
</div></div>
</div>
</div>



<div style="height:170px;" aria-hidden="true" class="wp-block-spacer"></div>



<p class="has-text-align-center"><strong>LISTEN ON<br></strong><a href="http://wordpress.com">Apple Podcasts</a> · <a href="http://wordpress.com">Stitcher</a> · <a href="http://wordpress.com">Spotify</a></p>
</div>
</main>


<div class="site-footer-container wp-block-template-part">
<div class="wp-container-61ddebb6ecd9a wp-block-group site-footer" style="padding-top:150px;padding-bottom: 150px">


<p class="has-text-align-center"><a href="https://wordpress.com/?ref=footer_blog" rel="nofollow">Blog at WordPress.com.</a></p>


</div>

</div>
</div>
    </div>
  );
}
