import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
<div className="flex min-h-screen justify-start items-start">
  <head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </head>

    <div className='w-screen bg-blue-400 flex flex-1 justify-start items-start'>

      glen


      
    </div>
</div>
  )
}
