import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import BackgroundWaves from "./components/BackgroundWaves";

export default function Home() {
  return (
    <div className="flex items-start justify-start bg-zinc-900 fullscreen">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>

      <div className="min-h-full">
        <div className="block">
          <BackgroundWaves />
        </div>
      </div>
    </div>
  );
}
