import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Logo from "../components/Logo";
import NavigationControl from "../components/NavigationControl";

export default function Home() {
  return (
    <div
      styles={{ zIndex: "-1" }}
      className="flex items-start justify-start min-h-screen bg-zinc-900 "
    >
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <div
        style={{
          height: "450px",
          width: "450px",
          opacity: "0.05",
          backgroundColor: "white",
          position: "fixed",
          transform: "rotate(30deg)",
          top: "-160px",
          zIndex: -10,
        }}
      />
      <div className="z-2">
        <Logo />
        <NavigationControl />
      </div>
    </div>
  );
}
