import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import BackgroundWaves from "./components/BackgroundWaves";

export default function Home() {
  return (
    <div className="flex items-start justify-start min-h-screen bg-zinc-900 ">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <div
        style={{
          height: "300px",
          width: "300px",
          opacity: "0.1",
          backgroundColor: "white",
          position: "fixed",
          left: "20px",
          transform: {transform: rotate(20deg);};
        }}
      >
        sgdgsf
      </div>
      <div className="min-h-full">
        <div className="hidden md:block">
          <BackgroundWaves />
        </div>
      </div>
    </div>
  );
}
