import Logo from "./Logo";
import NavigationControl from "./NavigationControl";
import Link from "next/link";
import BackgroundDesign from "./BackgroundDesign";
import { useState } from "react";

const Layout = ({ children }) => {
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);

  return (
    <>
      <div className="flex flex-row items-start justify-start -z-1 bg-zinc-900 ">
        <head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </head>
        <BackgroundDesign />
        <div className="z-10 flex items-end justify-between w-screen">
          <Logo />
          <div className="flex mr-10 text-3xl">
            <NavigationControl
              isOpen={isMobileMenuOpen}
              onOpen={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
            />
          </div>
        </div>
      </div>
      {isMobileMenuOpen && (
        <div className="flex justify-end mr-10 text-2xl border-2 sm:hidden">
          <div className="flex flex-col">
            <h1 className="title">
              <Link href="/projects">
                <a>Projects</a>
              </Link>
            </h1>
            <h1 className="title">
              <Link href="/about">
                <a>About</a>
              </Link>
            </h1>
            <h1 className="title">
              <Link href="/contactus">
                <a>Contact us</a>
              </Link>
            </h1>
          </div>
        </div>
      )}
    </>
  );
};

export default Layout;
