import Logo from "./Logo";
import NavigationControl from "./NavigationControl";

const Layout = ({ children }) => {
  return (
    <div className="flex items-start justify-start min-h-screen border-2 -z-1 bg-zinc-900 ">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <div
        style={{
          height: "450px",
          width: "450px",
          opacity: "0.05",
          backgroundColor: "white",
          position: "fixed",
          transform: "rotate(30deg)",
          top: "-160px",
          zIndex: 0,
        }}
      />
      <div className="z-10 flex items-end flex-1 w-screen">
        <Logo />
        <div className="flex flex-1 border-2">
          <NavigationControl />
        </div>
      </div>
      <div className="z-10 m-40">{children}</div>
    </div>
  );
};

export default Layout;
